# PostgreSQL. Versions 9.1 and up are supported

default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  host: localhost
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>

development:
  <<: *default
  database: turkopticon_development

test:
  <<: *default
  database: turkopticon_test

production:
  <<: *default
  database: turkopticon_production
  username: turkopticon
  password: <%= ENV['TURKOPTICON_PRODDB_PASSWORD'] %>
